// Form-schema projection from stock Hermes revision
// 3a056db7b1bb66e6601e4549b4074c4f2c35f838.
// Source/hash provenance: tools/contracts/hermes_task_blueprints.json.
// Copyright (c) 2025 Nous Research; MIT, tools/contracts/HERMES_LICENSE.txt.
// Verified against the canonical artifact at the fixture response boundary.
const stockTaskBlueprints = <Map<String, dynamic>>[
  {
    "key": "morning-brief",
    "title": "Morning briefing",
    "description":
        "A short daily briefing: today's calendar, weather, and anything urgent waiting on you.",
    "category": "daily",
    "tags": ["daily", "briefing"],
    "fields": [
      {
        "default": "08:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "important-mail",
    "title": "Important-mail monitor",
    "description":
        "Check your inbox periodically and ping you ONLY about mail that actually needs attention.",
    "category": "email",
    "tags": ["email", "monitor"],
    "fields": [
      {
        "default": "30",
        "options": ["15", "30", "60"],
        "optional": false,
        "strict": true,
        "help": "minutes between checks",
        "name": "interval_min",
        "type": "enum",
        "label": "How often?",
      },
      {
        "default":
            "needs a reply today, is from my manager or family, or mentions a deadline",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "criteria",
        "type": "text",
        "label": "Only notify me if the mail…",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "weekly-review",
    "title": "Weekly review",
    "description":
        "A weekly recap: what got done, what's still open, and what's coming up.",
    "category": "weekly",
    "tags": ["weekly", "review"],
    "fields": [
      {
        "default": "18:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "sunday",
        "options": ["sunday", "monday", "friday", "saturday"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "day",
        "type": "enum",
        "label": "Which day?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "workday-start",
    "title": "Workday start reminder",
    "description": "A weekday nudge with your agenda and top priorities.",
    "category": "daily",
    "tags": ["daily", "focus"],
    "fields": [
      {
        "default": "09:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "custom-reminder",
    "title": "Custom reminder",
    "description": "A recurring reminder in your own words, on your schedule.",
    "category": "general",
    "tags": ["reminder"],
    "fields": [
      {
        "default": "take a break and stretch",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "what",
        "type": "text",
        "label": "Remind me to…",
      },
      {
        "default": "14:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "everyday",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "evening-winddown",
    "title": "Evening wind-down",
    "description":
        "An end-of-day check-in: tomorrow's calendar at a glance and anything you should prep tonight.",
    "category": "daily",
    "tags": ["daily", "evening"],
    "fields": [
      {
        "default": "21:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "news-digest",
    "title": "Topic news digest",
    "description":
        "A recurring digest on a topic you care about — deduped against what was already sent, so only genuinely new items land.",
    "category": "general",
    "tags": ["digest", "research"],
    "fields": [
      {
        "default": "AI and technology",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "a subject, product, person, or search phrase",
        "name": "topic",
        "type": "text",
        "label": "What topic?",
      },
      {
        "default": "18:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "weekdays",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "5",
        "options": ["3", "5", "8"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "count",
        "type": "enum",
        "label": "How many bullets?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "bill-renewal-watch",
    "title": "Bills & renewals reminder",
    "description":
        "A heads-up before a recurring payment, subscription renewal, or due date — so nothing auto-charges by surprise.",
    "category": "general",
    "tags": ["reminder", "finance"],
    "fields": [
      {
        "default": "my streaming subscription renews soon",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "what",
        "type": "text",
        "label": "What's due?",
      },
      {
        "default": "10:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "everyday",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "price-watch",
    "title": "Price & availability watch",
    "description":
        "Watch an exact product, flight, hotel, or listing and alert when your price or availability condition is met.",
    "category": "general",
    "tags": ["prices", "shopping", "travel", "monitor"],
    "fields": [
      {
        "default": "a product URL or exact flight/hotel/listing description",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "URL or precise description — variant, dates, seller",
        "name": "item",
        "type": "text",
        "label": "What exactly to watch?",
      },
      {
        "default": "the all-in price drops below my target",
        "options": [],
        "optional": false,
        "strict": true,
        "help":
            "threshold price (state the currency), availability, or terms change",
        "name": "condition",
        "type": "text",
        "label": "Alert me when…",
      },
      {
        "default": "6",
        "options": ["1", "3", "6", "12", "24"],
        "optional": false,
        "strict": true,
        "help": "hours between checks — be gentle with rate limits",
        "name": "interval_h",
        "type": "enum",
        "label": "How often?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "competitor-watch",
    "title": "Competitor news watch",
    "description":
        "Track named companies for material news — launches, pricing, funding, filings — with a cited digest.",
    "category": "general",
    "tags": ["competitors", "news", "monitor", "research"],
    "fields": [
      {
        "default": "two or three competitors, by canonical name",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "canonical names and domains; aliases help dedup",
        "name": "companies",
        "type": "text",
        "label": "Which companies?",
      },
      {
        "default":
            "product launches, pricing changes, funding, partnerships, executive moves, incidents",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "categories",
        "type": "text",
        "label": "Which events matter?",
      },
      {
        "default": "09:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "monday",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "habit-checkin",
    "title": "Habit check-in",
    "description":
        "A recurring nudge to keep a habit on track and reflect on whether you did it.",
    "category": "general",
    "tags": ["habit", "wellbeing"],
    "fields": [
      {
        "default": "20 minutes of reading",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "habit",
        "type": "text",
        "label": "Which habit?",
      },
      {
        "default": "20:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "everyday",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "hydration-move",
    "title": "Hydration & movement nudge",
    "description":
        "A periodic nudge during the day to drink water, stand up, and stretch.",
    "category": "general",
    "tags": ["wellbeing", "focus"],
    "fields": [
      {
        "default": "1",
        "options": ["1", "2", "3"],
        "optional": false,
        "strict": true,
        "help": "hours between nudges",
        "name": "interval_hours",
        "type": "enum",
        "label": "How often?",
      },
      {
        "default": "9",
        "options": ["7", "8", "9", "10"],
        "optional": false,
        "strict": true,
        "help": "first hour of the active window (24h)",
        "name": "start_hour",
        "type": "enum",
        "label": "Start hour",
      },
      {
        "default": "17",
        "options": ["16", "17", "18", "19"],
        "optional": false,
        "strict": true,
        "help": "last hour of the active window (24h)",
        "name": "end_hour",
        "type": "enum",
        "label": "End hour",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "meal-plan",
    "title": "Weekly meal plan",
    "description":
        "A weekly meal plan plus a consolidated grocery list, tuned to your diet and how much time you have to cook.",
    "category": "weekly",
    "tags": ["weekly", "food"],
    "fields": [
      {
        "default": "no restrictions",
        "options": [
          "no restrictions",
          "vegetarian",
          "vegan",
          "high-protein",
          "low-carb",
        ],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "diet",
        "type": "enum",
        "label": "Diet?",
      },
      {
        "default": "dinner only",
        "options": ["dinner only", "lunch and dinner", "all three"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "meals",
        "type": "enum",
        "label": "Meals per day?",
      },
      {
        "default": "quick",
        "options": ["quick", "medium", "ambitious"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "effort",
        "type": "enum",
        "label": "Cooking effort?",
      },
      {
        "default": "17:00",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "sunday",
        "options": ["sunday", "monday", "friday", "saturday"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "day",
        "type": "enum",
        "label": "Which day?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "learn-daily",
    "title": "Daily learning drip",
    "description":
        "One bite-sized lesson a day on a topic you want to learn, building progressively over time.",
    "category": "daily",
    "tags": ["learning", "daily"],
    "fields": [
      {
        "default": "Spanish vocabulary",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "topic",
        "type": "text",
        "label": "Learn about…",
      },
      {
        "default": "08:30",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "weekdays",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "gratitude-journal",
    "title": "Gratitude & reflection prompt",
    "description":
        "A gentle evening prompt to reflect on the day and note what went well.",
    "category": "general",
    "tags": ["wellbeing", "reflection"],
    "fields": [
      {
        "default": "21:30",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "everyday",
        "options": ["everyday", "weekdays", "weekends"],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "recurrence",
        "type": "weekdays",
        "label": "Repeat on",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
  {
    "key": "on-this-day",
    "title": "On-this-day discovery",
    "description":
        "A daily dose of curiosity: a notable historical event, fact, or word for the day.",
    "category": "daily",
    "tags": ["daily", "curiosity"],
    "fields": [
      {
        "default": "on this day in history",
        "options": [
          "on this day in history",
          "word of the day",
          "science fact",
          "quote of the day",
        ],
        "optional": false,
        "strict": true,
        "help": "",
        "name": "flavor",
        "type": "enum",
        "label": "What kind?",
      },
      {
        "default": "07:30",
        "options": [],
        "optional": false,
        "strict": true,
        "help": "24h local time, e.g. 08:00",
        "name": "time",
        "type": "time",
        "label": "What time?",
      },
      {
        "default": "origin",
        "options": ["origin", "local", "telegram", "discord", "email"],
        "optional": false,
        "strict": false,
        "help":
            "origin = the chat you set this up from (or your configured home channel when created from the dashboard); local = save only, no message; or any connected platform name",
        "name": "deliver",
        "type": "enum",
        "label": "Where to deliver?",
      },
    ],
  },
];
